name: freezed_lint
version: 0.0.7
description: >
  Linter rules for freezed.
repository: https://github.com/rrousselGit/freezed
issue_tracker: https://github.com/rrousselGit/freezed/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.0.0
  analyzer_plugin: ^0.12.0
  custom_lint_builder: ^0.7.1
  freezed_annotation: ^2.4.4

dev_dependencies:
  custom_lint: ^0.7.1
  build_verify: ^3.1.0
  test: ^1.22.2
